version: '3.9'

services:
  web:
    build: .
    container_name: finmuse_backend
    ports:
      - "5001:5000"
    env_file:
      - .env.prod
    depends_on:
      - postgres
      - redis
    restart: always

  postgres:
    image: postgres:15
    container_name: finmuse_postgres
    restart: always
    environment:
      POSTGRES_USER: prod_user
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: finmuse
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: finmuse_redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  pgdata:
